### ISSUE TITLE
Did you manage to compile it successfully? 

### ISSUE THREAD

**Issue by gnukhaled** [bt4/overlay#1]
sys-apps/ipu6-camera-hal doesn't compile because <cstdint> is not included

`/var/tmp/portage/sys-apps/ipu6-camera-hal-9999/work/ipu6-camera-hal-cc0b859daeb5fdcdf23ed066ce0b6e313225fbb1/src/platformdata/gc/HalStream.h:55:5: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/var/tmp/portage/sys-apps/ipu6-camera-hal-9999/work/ipu6-camera-hal-cc0b859daeb5fdcdf23ed066ce0b6e313225fbb1/src/platformdata/gc/HalStream.h:62:5: error: ‘uint32_t’ does not name a type
   62 |     uint32_t mWidth;
      |     ^~~~~~~~
/var/tmp/portage/sys-apps/ipu6-camera-hal-9999/work/ipu6-camera-hal-cc0b859daeb5fdcdf23ed066ce0b6e313225fbb1/src/platformdata/gc/HalStream.h:62:5: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/var/tmp/portage/sys-apps/ipu6-camera-hal-9999/work/ipu6-camera-hal-cc0b859daeb5fdcdf23ed066ce0b6e313225fbb1/src/platformdata/gc/HalStream.h:63:5: error: ‘uint32_t’ does not name a type
   63 |     uint32_t mHeight;
      |     ^~~~~~~~
/var/tmp/portage/sys-apps/ipu6-camera-hal-9999/work/ipu6-camera-hal-cc0b859daeb5fdcdf23ed066ce0b6e313225fbb1/src/platformdata/gc/HalStream.h:63:5: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/var/tmp/portage/sys-apps/ipu6-camera-hal-9999/work/ipu6-camera-hal-cc0b859daeb5fdcdf23ed066ce0b6e313225fbb1/src/platformdata/gc/HalStream.h: In constructor ‘icamera::HalStream::HalStream(icamera::streamProps&, void*)’:
/var/tmp/portage/sys-apps/ipu6-camera-hal-9999/work/ipu6-camera-hal-cc0b859daeb5fdcdf23ed066ce0b6e313225fbb1/src/platformdata/gc/HalStream.h:43:15: error: class ‘icamera::HalStream’ does not have any field named ‘mWidth’
   43 |             : mWidth(props.width),
      |               ^~~~~~
/var/tmp/portage/sys-apps/ipu6-camera-hal-9999/work/ipu6-camera-hal-cc0b859daeb5fdcdf23ed066ce0b6e313225fbb1/src/platformdata/gc/HalStream.h:43:28: error: ‘struct icamera::streamProps’ has no member named ‘width’
   43 |             : mWidth(props.width),
      |                            ^~~~~
/var/tmp/portage/sys-apps/ipu6-camera-hal-9999/work/ipu6-camera-hal-cc0b859daeb5fdcdf23ed066ce0b6e313225fbb1/src/platformdata/gc/HalStream.h:44:15: error: class ‘icamera::HalStream’ does not have any field named ‘mHeight’
   44 |               mHeight(props.height),
      |               ^~~~~~~
/var/tmp/portage/sys-apps/ipu6-camera-hal-9999/work/ipu6-camera-hal-cc0b859daeb5fdcdf23ed066ce0b6e313225fbb1/src/platformdata/gc/HalStream.h:44:29: error: ‘struct icamera::streamProps’ has no member named ‘height’
   44 |               mHeight(props.height),
      |                             ^~~~~~
ninja: build stopped: subcommand failed.
 * ERROR: sys-apps/ipu6-camera-hal-9999::bt4 failed (compile phase):
 *   ninja -v -j12 -l12 failed
 * 
 * Call stack:
 *     ebuild.sh, line  136:  Called src_compile
 *   environment, line 2115:  Called cmake_src_compile
 *   environment, line  865:  Called cmake_build
 *   environment, line  832:  Called eninja
 *   environment, line 1301:  Called die
 * The specific snippet of code:
 *       "$@" || die -n "${*} failed"
 * 
 * If you need support, post the output of `emerge --info '=sys-apps/ipu6-camera-hal-9999::bt4'`,
 * the complete build log and the output of `emerge -pqv '=sys-apps/ipu6-camera-hal-9999::bt4'`.
 * The complete build log is located at '/var/tmp/portage/sys-apps/ipu6-camera-hal-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sys-apps/ipu6-camera-hal-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/sys-apps/ipu6-camera-hal-9999/work/ipu6-camera-hal-cc0b859daeb5fdcdf23ed066ce0b6e313225fbb1/ipu6'
 * S: '/var/tmp/portage/sys-apps/ipu6-camera-hal-9999/work/ipu6-camera-hal-cc0b859daeb5fdcdf23ed066ce0b6e313225fbb1/ipu6'

 * Messages for package sys-apps/ipu6-camera-hal-9999:

 * ERROR: sys-apps/ipu6-camera-hal-9999::bt4 failed (compile phase):
 *   ninja -v -j12 -l12 failed
 * 
 * Call stack:
 *     ebuild.sh, line  136:  Called src_compile
 *   environment, line 2115:  Called cmake_src_compile
 *   environment, line  865:  Called cmake_build
 *   environment, line  832:  Called eninja
 *   environment, line 1301:  Called die
 * The specific snippet of code:
 *       "$@" || die -n "${*} failed"
 * 
 * If you need support, post the output of `emerge --info '=sys-apps/ipu6-camera-hal-9999::bt4'`,
 * the complete build log and the output of `emerge -pqv '=sys-apps/ipu6-camera-hal-9999::bt4'`.
 * The complete build log is located at '/var/tmp/portage/sys-apps/ipu6-camera-hal-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sys-apps/ipu6-camera-hal-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/sys-apps/ipu6-camera-hal-9999/work/ipu6-camera-hal-cc0b859daeb5fdcdf23ed066ce0b6e313225fbb1/ipu6'
 * S: '/var/tmp/portage/sys-apps/ipu6-camera-hal-9999/work/ipu6-camera-hal-cc0b859daeb5fdcdf23ed066ce0b6e313225fbb1/ipu6'`

**Comment by bt4** [comment]
Hi, I don't have anything to test this on at present but I have updated the ebuild to use a different upstream commit which looks like it will fix this. Thanks.

**Comment by gnukhaled** [comment]
Thanks, But this is the current status


$ sudo emerge -av media-plugins/gst-plugins-icamerasrc

These are the packages that would be merged, in order:

Calculating dependencies / * Digest verification failed:
 * /var/db/repos/bt4/sys-apps/ipu6-camera-hal/ipu6-camera-hal-9999.ebuild
 * Reason: Failed on BLAKE2B verification
 * Got: 117cdfad858fab6927144b0de353bff857578520f1862b7adf6e5a3e5ab6b461627e476f6e16ed22a03e9ec4532668e5dd71d0e41f87a43912839cdb91159a21
 * Expected: d93c3c973c5adc4acf306145664acdd7de00bcf7aef729e5e5ae65cd46dcf85613c536882de40972389ab645a4fea9709eaa0e6b24b648890be4e9f37d6219b9
... done!
Dependency resolution took 2.00 s (backtrack: 1/20).


!!! All ebuilds that could satisfy "sys-apps/ipu6-camera-hal" have been masked.
!!! One of the following masked packages is required to complete your request:
- sys-apps/ipu6-camera-hal-9999::bt4 (masked by: corruption)

(dependency required by "media-plugins/gst-plugins-icamerasrc-9999::bt4" [ebuild])
(dependency required by "media-plugins/gst-plugins-icamerasrc" [argument])
For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.

**Comment by bt4** [comment]
Hi, thanks for testing. I need to regenerate the manifest after changing the ebuild. I don't have access to a Gentoo system at present but I should be able to do it at the end of the week.

**Comment by bt4** [comment]
Hi, I have updated the Manifest file. Please give it another try and let me know how you get on.

**Comment by gnukhaled** [comment]
Many thanks :-)

**Comment by gnukhaled** [comment]
ebuild compiles successfully and digest issue is fixed.
