### ISSUE TITLE
Are all the parts now necessary when ipu code has been integrated into kernel 6.10?

### ISSUE THREAD

**Issue by xfim** [bt4/overlay#9]
Now that the kernel has reached 6.10 and ipu modules are built in the kernel, are all the parts from this project necessary?

Thank you for your support,

**Comment by bt4** [comment]
Hi, this repository was based on the Fedora packages developed by Hans de Goede. Now Hans is working on a completely different stack using libcamera and pipewire which looks to me like a much better solution. I think it would be good to do the same on Gentoo, but I don't have the hardware to test it on at the moment.

**Comment by xfim** [comment]
Thank you very much @bt4 for your information and reply. I have found some information and will hopefully be able to point me towards the right direction.
